### ISSUE TITLE
test query script on real data

### ISSUE THREAD

**Issue by agladstein** [NCBI-Hackathons/RNA-Seq-in-the-Cloud#14]
And for results, obtain actual expression data (or locations of) to give to other teams

**Comment by mbernste** [comment]
Run it on this file: https://github.com/NCBI-Hackathons/RNA-Seq-in-the-Cloud/blob/master/Metadata/data/experiment_to_terms.json

Generate or find location of expression data to give to other teams

**Comment by emilyclough** [comment]
Make it work so that terms can have spaces

**Comment by agladstein** [comment]
8fb3a15517927a02552dc012e2f22cb1ff63fc8f
