### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by mbernste** [NCBI-Hackathons/RNA-Seq-in-the-Cloud#40]
When I run the Docker command in the README, I receive the following error, does anyone know why this might be? @agladstein 

``docker: Error response from daemon: pull access denied for ncbihackathons/metadata-notebook, repository does not exist or may require 'docker login'``

**Comment by agladstein** [comment]
Sorry! Typo.
Should be `ncbihackathons/metadata`
Corrected the image name in README in https://github.com/NCBI-Hackathons/RNA-Seq-in-the-Cloud/commit/b6ab20317e8ebb22dceb71bdbe87751438bf4be8

**Comment by mbernste** [comment]
Thanks!
