### ISSUE TITLE
Script to find all runs given a term

### ISSUE THREAD

**Issue by agladstein** [NCBI-Hackathons/RNA-Seq-in-the-Cloud#6]

**Comment by emilyclough** [comment]
3 main tasks:

1. Mapping run data to sample and mapping sample to ontology terms (ID) and then mapping to ontology term names. [Matt]

2. Jupiter notebook template

3. Fake data for creation of script. 

Runs: 1-100
Terms: 1-5
Study: 1-3

example:
Run| Term | Study
1         2           4
2        2           4
3        1           4
.
.
.

**Comment by emilyclough** [comment]
Revise on 3. Fake data for creation of query script.

Runs: 1-100
Terms: 1-5
Study: 1-3

Each run is associated with a subset of terms. In other words...
runs to terms
a:{1,23}
b: {2}
c:{3}

Study to runs.
A:{a}
B: {b,c}

**Comment by agladstein** [comment]
https://github.com/NCBI-Hackathons/RNA-Seq-in-the-Cloud/commit/d0f475e4ed2d9ecc034967d9fee85e7f32fb2e6d
